import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { PageShell, PageHeader } from "@/components/PageShell";
import { Button } from "@/components/ui/button";
import { fmtDate } from "@/lib/format";
import { Bell, AlertTriangle, Info, Check } from "lucide-react";

type Alert = {
  id: string;
  title: string;
  message: string | null;
  type: string;
  severity: "info" | "warning" | "critical";
  is_read: boolean;
  created_at: string;
};

const sevIcon = (s: string) =>
  s === "critical" ? AlertTriangle : s === "warning" ? Bell : Info;

const sevTone = (s: string) => {
  if (s === "critical")
    return { wrap: "bg-destructive/15 text-destructive", chip: "bg-destructive/15 text-destructive" };
  if (s === "warning")
    return { wrap: "bg-warning/15 text-warning", chip: "bg-warning/15 text-warning" };
  return {
    wrap: "bg-tertiary-container text-tertiary-on-container",
    chip: "bg-secondary-container text-secondary-on-container",
  };
};

export default function Alerts() {
  const { user } = useAuth();
  const [alerts, setAlerts] = useState<Alert[]>([]);

  const load = async () => {
    if (!user) return;
    const { data } = await supabase
      .from("alerts")
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(100);
    setAlerts((data as any) ?? []);
  };
  useEffect(() => {
    load();
  }, [user]);

  const markRead = async (id: string) => {
    await supabase.from("alerts").update({ is_read: true }).eq("id", id);
    load();
  };

  const markAll = async () => {
    if (!user) return;
    await supabase
      .from("alerts")
      .update({ is_read: true })
      .eq("user_id", user.id)
      .eq("is_read", false);
    load();
  };

  const unread = alerts.filter((a) => !a.is_read).length;

  return (
    <PageShell>
      <PageHeader
        title="Alerts"
        subtitle={`${unread} unread · auto-generated by database triggers`}
        actions={
          unread > 0 && (
            <Button variant="tonal" onClick={markAll}>
              <Check className="w-[18px] h-[18px]" />
              Mark all read
            </Button>
          )
        }
      />

      <div className="space-y-3">
        {alerts.length === 0 && (
          <div className="bg-surface-low rounded-3xl p-12 text-center text-muted-foreground body-medium shadow-e1">
            All quiet. No alerts yet.
          </div>
        )}
        {alerts.map((a) => {
          const Icon = sevIcon(a.severity);
          const tone = sevTone(a.severity);
          return (
            <div
              key={a.id}
              className={`bg-surface-low rounded-2xl p-4 flex items-start gap-4 shadow-e1 transition-all ${
                !a.is_read ? "ring-1 ring-primary/30" : "opacity-70"
              }`}
            >
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${tone.wrap}`}
              >
                <Icon className="w-[18px] h-[18px]" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1 flex-wrap">
                  <span className="title-medium">{a.title}</span>
                  <span
                    className={`label-small px-2 py-0.5 rounded-full capitalize ${tone.chip}`}
                  >
                    {a.type.replace("_", " ")}
                  </span>
                </div>
                {a.message && (
                  <p className="body-medium text-muted-foreground">{a.message}</p>
                )}
                <div className="label-small text-muted-foreground mt-1">
                  {fmtDate(a.created_at)}
                </div>
              </div>
              {!a.is_read && (
                <Button size="sm" variant="text" onClick={() => markRead(a.id)}>
                  Dismiss
                </Button>
              )}
            </div>
          );
        })}
      </div>
    </PageShell>
  );
}
