import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { PageShell, PageHeader } from "@/components/PageShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { fmtDate } from "@/lib/format";
import { Bell, AlertTriangle, Info, Check } from "lucide-react";

type Alert = {
  id: string; title: string; message: string | null;
  type: string; severity: "info" | "warning" | "critical";
  is_read: boolean; created_at: string;
};

const sevIcon = (s: string) => s === "critical" ? AlertTriangle : s === "warning" ? Bell : Info;
const sevColor = (s: string) =>
  s === "critical" ? "text-destructive border-destructive/40" :
  s === "warning" ? "text-warning border-warning/40" : "text-muted-foreground border-border";

export default function Alerts() {
  const { user } = useAuth();
  const [alerts, setAlerts] = useState<Alert[]>([]);

  const load = async () => {
    if (!user) return;
    const { data } = await supabase.from("alerts").select("*").eq("user_id", user.id).order("created_at", { ascending: false }).limit(100);
    setAlerts((data as any) ?? []);
  };
  useEffect(() => { load(); }, [user]);

  const markRead = async (id: string) => {
    await supabase.from("alerts").update({ is_read: true }).eq("id", id);
    load();
  };

  const markAll = async () => {
    if (!user) return;
    await supabase.from("alerts").update({ is_read: true }).eq("user_id", user.id).eq("is_read", false);
    load();
  };

  const unread = alerts.filter((a) => !a.is_read).length;

  return (
    <PageShell>
      <PageHeader
        title="Alerts"
        subtitle={`${unread} unread · auto-generated by database triggers`}
        actions={unread > 0 && <Button variant="outline" onClick={markAll}><Check className="w-4 h-4 mr-1" /> Mark all read</Button>}
      />

      <div className="space-y-2">
        {alerts.length === 0 && (
          <div className="glass-card p-12 text-center text-muted-foreground">All quiet. No alerts yet.</div>
        )}
        {alerts.map((a) => {
          const Icon = sevIcon(a.severity);
          return (
            <div key={a.id} className={`glass-card p-4 flex items-start gap-3 ${!a.is_read ? "ring-1 ring-primary/20" : "opacity-70"}`}>
              <div className={`w-9 h-9 rounded-lg border flex items-center justify-center shrink-0 ${sevColor(a.severity)}`}>
                <Icon className="w-4 h-4" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-medium">{a.title}</span>
                  <Badge variant="outline" className="text-[10px] capitalize">{a.type.replace("_", " ")}</Badge>
                </div>
                {a.message && <p className="text-sm text-muted-foreground">{a.message}</p>}
                <div className="text-xs text-muted-foreground mt-1">{fmtDate(a.created_at)}</div>
              </div>
              {!a.is_read && (
                <Button size="sm" variant="ghost" onClick={() => markRead(a.id)}>Dismiss</Button>
              )}
            </div>
          );
        })}
      </div>
    </PageShell>
  );
}
